const video=document.getElementById('video'),canvas=document.getElementById('overlay'),ctx=canvas.getContext('2d');
const startBtn=document.getElementById('startBtn'),scanBtn=document.getElementById('scanBtn'),unlockBtn=document.getElementById('unlockBtn'),replyBtn=document.getElementById('replyBtn');
const camStatus=document.getElementById('camStatus'),lockStatus=document.getElementById('lockStatus'),unlockMsg=document.getElementById('unlockMsg'),nameInput=document.getElementById('nameInput'),reason=document.getElementById('reason');
const cuteNum=document.getElementById('cuteNum'),smileNum=document.getElementById('smileNum'),glowNum=document.getElementById('glowNum'),effectNum=document.getElementById('effectNum');
const line1=document.getElementById('line1'),line2=document.getElementById('line2'),line3=document.getElementById('line3'),quote=document.getElementById('quote'),replyBox=document.getElementById('replyBox');
let stream=null,unlocked=false,selectedMood='happy';
const effects=['unstable 😄','very high ✨','serious 💗','dangerous 🌸','off the charts 💫','repeat-worthy 😌'];
const scanLines={
happy:["Aaj wali smile dangerous category me aa rahi hai — Dhanesh detector confirm karta hai.","Happy Lavanya detected. Recovery time unknown.","Tum khush hoti ho to pura frame better lagta hai.","Aaj ka smile version save kar lena chahiye tha."],
calm:["Aaj calm version detect hua hai… aur honestly ye bhi kaafi pretty hai.","Soft calm vibe + tum = detector ne extra points de diye.","Shant mood me bhi tum normal wali category me aati hi nahi.","Calm reading clean hai, effect phir bhi strong hai."],
sad:["Mood low ho sakta hai… par tum phir bhi achhi ho, isme koi minus nahi aata.","Aaj heavy feel ho raha ho to bhi tumhari softness waisi hi hai.","Low mood detected. Reminder: tum messy day me bhi less lovely nahi hoti.","Aaj halka feel na ho to bhi theek hai… tum abhi bhi worth noticing ho."],
overthinking:["Overthinking level high, but pretty level usse bhi high hai.","Dimag fast chal raha hai, par tumhari value us speed se change nahi hoti.","Scanner note: thoughts loud hain, par tum phir bhi soft ho.","Overthinking detected. Breathing slow, pretty score unchanged."]
};
function resizeCanvas(){const rect=video.getBoundingClientRect();canvas.width=rect.width*devicePixelRatio;canvas.height=rect.height*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}window.addEventListener('resize',resizeCanvas);
async function startCamera(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});video.srcObject=stream;await video.play();camStatus.textContent='Camera on';resizeCanvas();drawFrame()}catch(err){camStatus.textContent='Camera blocked';line1.innerHTML='<strong>Status:</strong> camera permission nahi mili.';line2.innerHTML='<strong>Fix:</strong> browser me camera allow karo.';line3.innerHTML='<strong>Note:</strong> phir page refresh karke dubara try karo.'}}
function drawFrame(){if(!stream)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.strokeStyle=unlocked?'rgba(255,142,187,.95)':'rgba(109,255,211,.95)';ctx.lineWidth=2;const w=video.clientWidth*.48,h=video.clientHeight*.54,x=(video.clientWidth-w)/2,y=(video.clientHeight-h)/2-10;ctx.strokeRect(x,y,w,h);ctx.fillStyle=unlocked?'rgba(255,142,187,.95)':'rgba(109,255,211,.92)';ctx.font='12px sans-serif';ctx.fillText(unlocked?'Lavanya-only scan active':'Camera frame ready',x+8,Math.max(18,y-10));requestAnimationFrame(drawFrame)}
function unlockScanner(){const val=(nameInput.value||'').trim().toLowerCase();if(val==='lavanya'||val==='lavanya sharma'||val==='lavo'){unlocked=true;lockStatus.textContent='Unlocked: Lavanya detected 💗';unlockMsg.textContent='Scanner unlocked successfully.';line1.innerHTML='<strong>Lock:</strong> Lavanya-only mode active.';line2.innerHTML='<strong>Status:</strong> ab mood scan aur replies dono ready hain.';line3.innerHTML='<strong>Note:</strong> fresh reply Groq se aayega.'}else{unlocked=false;lockStatus.textContent='Access denied';unlockMsg.textContent='This scanner is reserved for Lavanya only 💗';line1.innerHTML='<strong>Access denied:</strong> this scanner is reserved for Lavanya only.';line2.innerHTML='<strong>Status:</strong> naam match nahi hua.';line3.innerHTML='<strong>Tip:</strong> only Lavanya can unlock this page.'}}
function runScan(){if(!unlocked){line1.innerHTML='<strong>Lock:</strong> pehle Lavanya-only unlock chahiye.';line2.innerHTML='<strong>Reason:</strong> ye scanner reserved hai.';line3.innerHTML='<strong>Verdict:</strong> unlock ke baad hi mood scan chalega.';return}const seed=Date.now()%997;const ranges={happy:{cute:[95,100],smile:[94,100],glow:[93,99]},calm:{cute:[93,98],smile:[82,91],glow:[90,97]},sad:{cute:[92,97],smile:[58,76],glow:[85,94]},overthinking:{cute:[93,98],smile:[65,82],glow:[87,95]}};const r=ranges[selectedMood];const pick=([min,max],n)=>min+(n%(max-min+1));const cute=pick(r.cute,seed),smile=pick(r.smile,seed*3),glow=pick(r.glow,seed*5),effect=effects[seed%effects.length],q=scanLines[selectedMood][seed%scanLines[selectedMood].length];cuteNum.textContent=cute+'%';smileNum.textContent=smile+'%';glowNum.textContent=glow+'%';effectNum.textContent=effect;line1.innerHTML=`<strong>Mood:</strong> ${selectedMood} detected in Lavanya-only mode.`;line2.innerHTML=`<strong>Smile reading:</strong> ${smile}% — is mood ke hisaab se kaafi achha result hai.`;line3.innerHTML=`<strong>Cuteness reading:</strong> ${cute}% — yeh score kam aana mushkil hi tha.`;quote.textContent=q}
async function getReply(){if(!unlocked){replyBox.innerHTML='<strong>Reply:</strong> pehle Lavanya-only unlock chahiye.';return}replyBox.innerHTML='<strong>Reply:</strong> soch raha hoon…';try{const res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mood:selectedMood,reason:reason.value.trim()})});const data=await res.json();if(!res.ok) throw new Error(data.error||'Request failed');replyBox.innerHTML=`<strong>Reply:</strong> ${data.text}`}catch(err){replyBox.innerHTML=`<strong>Reply:</strong> ${err.message}`}}
document.querySelectorAll('.mood').forEach(el=>{el.addEventListener('click',()=>{document.querySelectorAll('.mood').forEach(x=>x.classList.remove('active'));el.classList.add('active');selectedMood=el.dataset.mood})});
startBtn.addEventListener('click',startCamera);unlockBtn.addEventListener('click',unlockScanner);scanBtn.addEventListener('click',runScan);replyBtn.addEventListener('click',getReply);
